version: '3.4'

services:
  flowable-db:
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - data_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flowable
      - POSTGRES_USER=flowable
      - POSTGRES_PASSWORD=flowable

  flowable-modeler:
    image: flowable/flowable-modeler:6.5.0
    ports:
      - 8091:8888
    environment:
      - SERVER_PORT=8888
      - SERVER_SERVLET_CONTEXT-PATH=/
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm:8080
      - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://localhost:8093
      - FLOWABLE_COMMON_APP_IDM-ADMIN.USER=admin
      - FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=test
      - FLOWABLE_MODELER_APP_DEPLOYMENT-API-URL=http://flowable-task:9999/flowable-task/app-api

  flowable-admin:
    image: flowable/flowable-admin:6.5.0
    ports:
      - 8092:9988
    environment:
      - SERVER_PORT=9988
      - SERVER_SERVLET_CONTEXT-PATH=/
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm:8080
      - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://localhost:8093
      - FLOWABLE_COMMON_APP_IDM-ADMIN.USER=admin
      - FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=test
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_PROCESS_REST-ROOT=process-api
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CMMN_REST-ROOT=cmmn-api
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_DMN_REST-ROOT=dmn-api
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_FORM_REST-ROOT=form-api
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_CONTENT_REST-ROOT=content-api
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_SERVER-ADDRESS=http://host.docker.internal
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_PORT=8090
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_CONTEXT-ROOT=/
      - FLOWABLE_ADMIN_APP_SERVER-CONFIG_APP_REST-ROOT=app-api

  flowable-idm:
    image: flowable/flowable-idm:6.5.0
    ports:
      - 8093:8080
    environment:
      - SERVER_PORT=8080
      - SERVER_SERVLET_CONTEXT-PATH=/
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable

  flowable-task:
    image: flowable/flowable-task:6.5.0
    ports:
      - 8094:9999
    environment:
      - SERVER_PORT=9999
      #- SERVER_SERVLET_CONTEXT-PATH=/ #currently not possible: check https://github.com/flowable/flowable-engine/issues/2026
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://flowable-db:5432/flowable
      - SPRING_DATASOURCE_USERNAME=flowable
      - SPRING_DATASOURCE_PASSWORD=flowable
      - FLOWABLE_COMMON_APP_IDM-URL=http://flowable-idm:8080
      - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://localhost:8093
      - FLOWABLE_COMMON_APP_IDM-ADMIN.USER=admin
      - FLOWABLE_COMMON_APP_IDM-ADMIN.PASSWORD=test

volumes:
  data_db: